let electron = require("electron");
//#region electron/preload.ts
electron.contextBridge.exposeInMainWorld("api", {
	getSettings: () => electron.ipcRenderer.invoke("get-settings"),
	updateSettings: (settings) => electron.ipcRenderer.invoke("update-settings", settings),
	getTechnicians: () => electron.ipcRenderer.invoke("get-technicians"),
	addTechnician: (name, profit_percentage) => electron.ipcRenderer.invoke("add-technician", name, profit_percentage),
	editTechnician: (id, name, profit_percentage) => electron.ipcRenderer.invoke("edit-technician", id, name, profit_percentage),
	deleteTechnician: (id) => electron.ipcRenderer.invoke("delete-technician", id),
	getOperations: () => electron.ipcRenderer.invoke("get-operations"),
	addOperation: (op) => electron.ipcRenderer.invoke("add-operation", op),
	editOperation: (id, op) => electron.ipcRenderer.invoke("edit-operation", id, op),
	deleteOperation: (id) => electron.ipcRenderer.invoke("delete-operation", id),
	importOperationsExcel: () => electron.ipcRenderer.invoke("import-operations-excel"),
	importOperationsExcelData: (data) => electron.ipcRenderer.invoke("import-operations-excel-data", data),
	getDebts: () => electron.ipcRenderer.invoke("get-debts"),
	payDebt: (id) => electron.ipcRenderer.invoke("pay-debt", id),
	getWithdrawals: () => electron.ipcRenderer.invoke("get-withdrawals"),
	addWithdrawal: (w) => electron.ipcRenderer.invoke("add-withdrawal", w),
	editWithdrawal: (id, w) => electron.ipcRenderer.invoke("edit-withdrawal", id, w),
	deleteWithdrawal: (id) => electron.ipcRenderer.invoke("delete-withdrawal", id),
	getIcCompatibilities: () => electron.ipcRenderer.invoke("get-ic-compatibilities"),
	addIcCompatibility: (ic) => electron.ipcRenderer.invoke("add-ic-compatibility", ic),
	editIcCompatibility: (id, ic) => electron.ipcRenderer.invoke("edit-ic-compatibility", id, ic),
	deleteIcCompatibility: (id) => electron.ipcRenderer.invoke("delete-ic-compatibility", id),
	importIcExcel: () => electron.ipcRenderer.invoke("import-ic-excel"),
	importIcExcelData: (data) => electron.ipcRenderer.invoke("import-ic-excel-data", data),
	getScrapDevices: () => electron.ipcRenderer.invoke("get-scrap-devices"),
	addScrapDevice: (data) => electron.ipcRenderer.invoke("add-scrap-device", data),
	editScrapDevice: (id, data) => electron.ipcRenderer.invoke("edit-scrap-device", id, data),
	deleteScrapDevice: (id) => electron.ipcRenderer.invoke("delete-scrap-device", id),
	getQuickLists: () => electron.ipcRenderer.invoke("get-quick-lists"),
	addQuickListItem: (type, item) => electron.ipcRenderer.invoke("add-quick-list-item", type, item),
	removeQuickListItem: (type, item) => electron.ipcRenderer.invoke("remove-quick-list-item", type, item),
	getDashboardStats: () => electron.ipcRenderer.invoke("get-dashboard-stats"),
	getTechnicianStats: () => electron.ipcRenderer.invoke("get-technician-stats"),
	closeMonth: (newCapital) => electron.ipcRenderer.invoke("close-month", newCapital),
	closeMonthWithExcel: (newCapital) => electron.ipcRenderer.invoke("close-month-with-excel", newCapital),
	getAllOperations: () => electron.ipcRenderer.invoke("get-all-operations"),
	factoryReset: () => electron.ipcRenderer.invoke("factory-reset"),
	restartApp: () => electron.ipcRenderer.invoke("restart-app"),
	createBackup: () => electron.ipcRenderer.invoke("backup:create"),
	listBackups: () => electron.ipcRenderer.invoke("backup:list"),
	restoreBackup: (filename) => electron.ipcRenderer.invoke("backup:restore", filename)
});
//#endregion
